__main__ - optimizer_entrypoint(line:935) - !!! Skip optimizer !!! all root_node_rps all regions are 0
__main__ - optimizer_entrypoint(line:935) - !!! Skip optimizer !!! all root_node_rps all regions are 0
__main__ - optimizer_entrypoint(line:935) - !!! Skip optimizer !!! all root_node_rps all regions are 0
__main__ - optimizer_entrypoint(line:935) - !!! Skip optimizer !!! all root_node_rps all regions are 0
__main__ - optimizer_entrypoint(line:935) - !!! Skip optimizer !!! all root_node_rps all regions are 0
__main__ - optimizer_entrypoint(line:935) - !!! Skip optimizer !!! all root_node_rps all regions are 0
__main__ - optimizer_entrypoint(line:935) - !!! Skip optimizer !!! all root_node_rps all regions are 0
__main__ - optimizer_entrypoint(line:935) - !!! Skip optimizer !!! all root_node_rps all regions are 0
__main__ - optimizer_entrypoint(line:935) - !!! Skip optimizer !!! all root_node_rps all regions are 0
__main__ - optimizer_entrypoint(line:935) - !!! Skip optimizer !!! all root_node_rps all regions are 0
global_controller - log_exception(line:838) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 611, in handleProxyLoad
    temp_df = verify_return_df(temp_df, region)
  File "/app/global_controller.py", line 366, in verify_return_df
    assert row['dst_endpoint'] in aggregated_rps[row['dst_cid']][row['dst_svc']]
AssertionError
global_controller - log_exception(line:838) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 611, in handleProxyLoad
    temp_df = verify_return_df(temp_df, region)
  File "/app/global_controller.py", line 366, in verify_return_df
    assert row['dst_endpoint'] in aggregated_rps[row['dst_cid']][row['dst_svc']]
AssertionError
global_controller - log_exception(line:838) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 611, in handleProxyLoad
    temp_df = verify_return_df(temp_df, region)
  File "/app/global_controller.py", line 366, in verify_return_df
    assert row['dst_endpoint'] in aggregated_rps[row['dst_cid']][row['dst_svc']]
AssertionError
global_controller - log_exception(line:838) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 611, in handleProxyLoad
    temp_df = verify_return_df(temp_df, region)
  File "/app/global_controller.py", line 366, in verify_return_df
    assert row['dst_endpoint'] in aggregated_rps[row['dst_cid']][row['dst_svc']]
AssertionError
global_controller - log_exception(line:838) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 611, in handleProxyLoad
    temp_df = verify_return_df(temp_df, region)
  File "/app/global_controller.py", line 366, in verify_return_df
    assert row['dst_endpoint'] in aggregated_rps[row['dst_cid']][row['dst_svc']]
AssertionError
global_controller - log_exception(line:838) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 611, in handleProxyLoad
    temp_df = verify_return_df(temp_df, region)
  File "/app/global_controller.py", line 366, in verify_return_df
    assert row['dst_endpoint'] in aggregated_rps[row['dst_cid']][row['dst_svc']]
AssertionError
global_controller - log_exception(line:838) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 611, in handleProxyLoad
    temp_df = verify_return_df(temp_df, region)
  File "/app/global_controller.py", line 366, in verify_return_df
    assert row['dst_endpoint'] in aggregated_rps[row['dst_cid']][row['dst_svc']]
AssertionError
global_controller - log_exception(line:838) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 611, in handleProxyLoad
    temp_df = verify_return_df(temp_df, region)
  File "/app/global_controller.py", line 366, in verify_return_df
    assert row['dst_endpoint'] in aggregated_rps[row['dst_cid']][row['dst_svc']]
AssertionError
global_controller - log_exception(line:838) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 611, in handleProxyLoad
    temp_df = verify_return_df(temp_df, region)
  File "/app/global_controller.py", line 366, in verify_return_df
    assert row['dst_endpoint'] in aggregated_rps[row['dst_cid']][row['dst_svc']]
AssertionError
global_controller - log_exception(line:838) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 611, in handleProxyLoad
    temp_df = verify_return_df(temp_df, region)
  File "/app/global_controller.py", line 366, in verify_return_df
    assert row['dst_endpoint'] in aggregated_rps[row['dst_cid']][row['dst_svc']]
AssertionError
global_controller - log_exception(line:838) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 611, in handleProxyLoad
    temp_df = verify_return_df(temp_df, region)
  File "/app/global_controller.py", line 366, in verify_return_df
    assert row['dst_endpoint'] in aggregated_rps[row['dst_cid']][row['dst_svc']]
AssertionError
global_controller - log_exception(line:838) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 611, in handleProxyLoad
    temp_df = verify_return_df(temp_df, region)
  File "/app/global_controller.py", line 366, in verify_return_df
    assert row['dst_endpoint'] in aggregated_rps[row['dst_cid']][row['dst_svc']]
AssertionError
__main__ - optimizer_entrypoint(line:935) - !!! Skip optimizer !!! all root_node_rps all regions are 0
__main__ - optimizer_entrypoint(line:935) - !!! Skip optimizer !!! all root_node_rps all regions are 0
__main__ - optimizer_entrypoint(line:935) - !!! Skip optimizer !!! all root_node_rps all regions are 0
__main__ - optimizer_entrypoint(line:935) - !!! Skip optimizer !!! all root_node_rps all regions are 0
__main__ - optimizer_entrypoint(line:935) - !!! Skip optimizer !!! all root_node_rps all regions are 0
__main__ - optimizer_entrypoint(line:935) - !!! Skip optimizer !!! all root_node_rps all regions are 0
__main__ - optimizer_entrypoint(line:935) - !!! Skip optimizer !!! all root_node_rps all regions are 0
__main__ - optimizer_entrypoint(line:935) - !!! Skip optimizer !!! all root_node_rps all regions are 0
__main__ - optimizer_entrypoint(line:935) - !!! Skip optimizer !!! all root_node_rps all regions are 0
__main__ - optimizer_entrypoint(line:935) - !!! Skip optimizer !!! all root_node_rps all regions are 0
__main__ - optimizer_entrypoint(line:935) - !!! Skip optimizer !!! all root_node_rps all regions are 0
