__main__ - optimizer_entrypoint(line:935) - !!! Skip optimizer !!! all root_node_rps all regions are 0
__main__ - optimizer_entrypoint(line:935) - !!! Skip optimizer !!! all root_node_rps all regions are 0
__main__ - optimizer_entrypoint(line:935) - !!! Skip optimizer !!! all root_node_rps all regions are 0
__main__ - optimizer_entrypoint(line:935) - !!! Skip optimizer !!! all root_node_rps all regions are 0
__main__ - optimizer_entrypoint(line:935) - !!! Skip optimizer !!! all root_node_rps all regions are 0
apscheduler.executors.default - run_job(line:131) - Job "optimizer_entrypoint (trigger: interval[0:00:01], next run at: 2024-04-27 05:02:27 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/app/global_controller.py", line 981, in optimizer_entrypoint
    cur_percentage_df, desc = opt.run_optimizer(\
  File "/app/optimizer_test.py", line 547, in run_optimizer
    incoming = endpoint_level_rps[cid][root_ep_svc_name][root_ep]
KeyError: 'sslateingress@POST@/heavy'
global_controller - log_exception(line:838) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 611, in handleProxyLoad
    temp_df = verify_return_df(temp_df, region)
  File "/app/global_controller.py", line 366, in verify_return_df
    assert row['dst_endpoint'] in aggregated_rps[row['dst_cid']][row['dst_svc']]
AssertionError
global_controller - log_exception(line:838) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 611, in handleProxyLoad
    temp_df = verify_return_df(temp_df, region)
  File "/app/global_controller.py", line 366, in verify_return_df
    assert row['dst_endpoint'] in aggregated_rps[row['dst_cid']][row['dst_svc']]
AssertionError
global_controller - log_exception(line:838) - Exception on /proxyLoad [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/global_controller.py", line 611, in handleProxyLoad
    temp_df = verify_return_df(temp_df, region)
  File "/app/global_controller.py", line 366, in verify_return_df
    assert row['dst_endpoint'] in aggregated_rps[row['dst_cid']][row['dst_svc']]
AssertionError
